#!/usr/bin/env bash
# Pod setup for milestone 7 (2B -> 0.8B distillation on BEA-60K). Same
# documented image and torch/cudnn recipe as setup_llm_judge.sh
# (runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04; torch==2.5.1+cu124
# for Qwen3.5 support under transformers>=5.5; force-installed nvidia-cudnn-cu12
# because the image's system libcudnn.so.9 is not on the venv's linker path).
# On top of that this adds: peft, bitsandbytes, datasets (QLoRA fine-tuning),
# and a best-effort flash-attn build (optimized attention kernel; training
# proceeds on the SDPA fallback if the build fails or times out).
set -uo pipefail

REPO_DIR="${REPO_DIR:-/workspace/spell-corrector}"
IMAGE_PYTHON="${IMAGE_PYTHON:-$(command -v python3 || command -v python)}"
VENV="${VENV:-/workspace/venv}"
NVIDIA_ENV_FILE="${NVIDIA_ENV_FILE:-/workspace/llm-judge-env.sh}"
export IMAGE_PYTHON
cd "$REPO_DIR"

log() { printf '\n=== %s (%ss) ===\n' "$1" "$SECONDS"; }
die() { echo "SETUP FAILED: $1"; exit 1; }

case "$VENV" in
  ""|"/"|"/usr"|"/usr/bin"|"/workspace") die "refusing to rm -rf VENV=$VENV" ;;
esac

use_venv_python() {
  PYTHON="$VENV/bin/python"
  export PYTHON
  export PATH="$VENV/bin:$PATH"
  mkdir -p /workspace
  printf '%s\n' "$PYTHON" > /workspace/python-interpreter
}

pip_install() {
  local log="$1"; shift
  echo "+ $PYTHON -m pip install $*" | tee "$log"
  if ! "$PYTHON" -m pip install "$@" >>"$log" 2>&1; then
    echo "----- $log -----"
    tail -80 "$log"
    return 1
  fi
  cat "$log"
  return 0
}

force_install_nvidia_libs() {
  local nvidia_pkgs=()
  local line
  while IFS= read -r line; do
    [ -n "$line" ] && nvidia_pkgs+=("$line")
  done < <("$PYTHON" -m pip freeze | grep -i '^nvidia-' || true)
  if [ "${#nvidia_pkgs[@]}" -eq 0 ]; then
    nvidia_pkgs=(nvidia-cudnn-cu12)
  fi
  pip_install /tmp/pip-nvidia.log --ignore-installed --no-deps "${nvidia_pkgs[@]}" \
    || die "pip nvidia CUDA/cudnn libs into venv"
}

export_nvidia_ld_library_path() {
  local computed
  computed="$("$PYTHON" - <<'PY'
import os
import pathlib
import site

dirs = []
seen = set()
roots = [pathlib.Path(p) for p in site.getsitepackages()]
user = site.getusersitepackages()
if user:
    roots.append(pathlib.Path(user))
for root in roots:
    nvidia = root / "nvidia"
    if not nvidia.is_dir():
        continue
    for lib in list(nvidia.glob("*/lib")) + list(nvidia.glob("*/lib64")):
        if lib.is_dir():
            resolved = str(lib.resolve())
            if resolved not in seen:
                seen.add(resolved)
                dirs.append(resolved)
existing = [p for p in os.environ.get("LD_LIBRARY_PATH", "").split(":") if p and p not in seen]
print(":".join(dirs + existing))
PY
)"
  export LD_LIBRARY_PATH="$computed"
  mkdir -p "$(dirname "$NVIDIA_ENV_FILE")"
  {
    echo "# Generated by setup_distill.sh — nvidia pip lib dirs for libcudnn.so.9"
    printf 'export LD_LIBRARY_PATH=%q\n' "$LD_LIBRARY_PATH"
  } > "$NVIDIA_ENV_FILE"
  echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
  echo "wrote $NVIDIA_ENV_FILE"
}

log "CUDA check ($IMAGE_PYTHON)"
nvidia-smi || echo "nvidia-smi unavailable"

# Fail fast (seconds, not the ~2min of pip installs below) if the CONTAINER
# itself can't reach CUDA -- nvidia-smi only needs NVML/the driver, but the
# CUDA runtime API additionally needs /dev/nvidia-uvm mapped and
# NVIDIA_DRIVER_CAPABILITIES to include "compute". A container missing that
# shows exactly this split: nvidia-smi works, torch.cuda.is_available() does
# not, regardless of which torch build is asked to check.
log "container GPU-passthrough diagnostic"
echo "NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-unset}"
echo "NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-unset}"
ls -l /dev/nvidia* 2>&1 || echo "no /dev/nvidia* device nodes"
"$IMAGE_PYTHON" - <<'PY' || echo "base-image torch cannot see CUDA (pre-existing container issue, not this script)"
try:
    import torch
    print("base torch", torch.__version__, "cuda avail", torch.cuda.is_available())
except Exception as e:
    print("base image has no usable torch:", e)
PY

log "apt: hunspell + venv/dev headers"
(
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq --no-install-recommends \
    git curl ca-certificates hunspell libhunspell-dev hunspell-en-us ninja-build
  pyver="$("$IMAGE_PYTHON" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
  apt-get install -y -qq --no-install-recommends \
    "python${pyver}-venv" "python${pyver}-dev" \
    || apt-get install -y -qq --no-install-recommends python3-venv python3-dev
) >/tmp/apt.log 2>&1 || { tail -30 /tmp/apt.log; die "apt"; }
log "apt done"

log "venv $VENV --system-site-packages"
rm -rf "$VENV"
"$IMAGE_PYTHON" -m venv --system-site-packages "$VENV" || die "venv"
use_venv_python
echo "venv python=$PYTHON ($($PYTHON -V 2>&1))"
if ! "$PYTHON" -m pip --version >/dev/null 2>&1; then
  "$PYTHON" -m ensurepip --upgrade || die "ensurepip"
fi

log "pip base deps"
pip_install /tmp/pip-upgrade.log --upgrade pip || die "pip upgrade"
pip_install /tmp/pip-deps.log numpy requests pytest pyyaml || die "pip deps"
pip_install /tmp/pip-build.log "setuptools<60" wheel cython || die "pip build deps"
pip_install /tmp/hunspell-pip.log --no-build-isolation --force-reinstall hunspell==0.5.5 \
  || die "hunspell pip install into ${PYTHON}"

# Same torch pin as the LLM-judge track: 2.5.1+cu124 (Qwen3.5 under
# transformers>=5.5 needs DTensor-era torch); never cu128 on a CUDA 12.4 host.
log "torch==2.5.1+cu124"
if "$PYTHON" - <<'PY'
import sys
import torch

ver = tuple(int(p) for p in torch.__version__.split("+", 1)[0].split(".")[:2])
cuda = torch.version.cuda or ""
if ver >= (2, 5) and cuda.startswith("12.4") and torch.cuda.is_available():
    sys.exit(0)
sys.exit(1)
PY
then
  echo "venv already has CUDA-available torch>=2.5+cu124; skipping wheel download"
else
  pip_install /tmp/pip-torch.log --upgrade "torch==2.5.1" \
    --index-url https://download.pytorch.org/whl/cu124 \
    || die "pip torch==2.5.1+cu124"
  log "nvidia-* into venv (libcudnn.so.9)"
  force_install_nvidia_libs
fi
export_nvidia_ld_library_path

log "CUDA check (venv torch after cu124 install)"
# Retry a few times with a short pause: a fresh process right after installing
# new nvidia-* wheels has occasionally raced a container's GPU attachment on
# Runpod's community cloud, and torch.cuda.is_available() in a brand new
# process is cheap enough to just try again rather than fail the whole pod.
CUDA_OK=0
for attempt in 1 2 3 4 5; do
  if "$PYTHON" - <<'PY'
import torch
print("torch", torch.__version__, "cuda", torch.version.cuda, "avail", torch.cuda.is_available())
if not torch.cuda.is_available():
    raise SystemExit(1)
if "cu128" in torch.__version__:
    raise SystemExit(1)
print("gpu", torch.cuda.get_device_name(0), "bf16", torch.cuda.is_bf16_supported())
PY
  then
    CUDA_OK=1
    break
  fi
  echo "CUDA check attempt $attempt/5 failed; retrying in 10s..."
  sleep 10
done
[ "$CUDA_OK" -eq 1 ] || die "CUDA-available torch>=2.5.1+cu124 missing after 5 attempts"

log "transformers/accelerate/peft/bitsandbytes/datasets"
pip_install /tmp/pip-transformers.log "transformers>=5.5" "accelerate>=0.34" \
  || die "pip transformers/accelerate"
pip_install /tmp/pip-peft.log "peft>=0.21" "bitsandbytes>=0.50" "datasets>=2.20" \
  || die "pip peft/bitsandbytes/datasets"

log "flash-attn (optimized attention kernel, best-effort)"
FLASH_OK=0
if timeout 900 "$PYTHON" -m pip install flash-attn --no-build-isolation >/tmp/pip-flash.log 2>&1; then
  FLASH_OK=1
  echo "flash-attn installed"
else
  echo "flash-attn build failed or timed out; training falls back to SDPA"
  tail -40 /tmp/pip-flash.log || true
fi
echo "FLASH_OK=$FLASH_OK" >> "$NVIDIA_ENV_FILE"

log "hunspell import check"
"$PYTHON" -c "import hunspell; print('hunspell', hunspell.__file__)" || die "import hunspell"

log "verifying peft/bitsandbytes/transformers stack"
"$PYTHON" - <<'PY' || die "verify"
import torch, transformers, peft, bitsandbytes, datasets
print("torch", torch.__version__, "cuda avail", torch.cuda.is_available())
print("transformers", transformers.__version__)
print("peft", peft.__version__)
print("bitsandbytes", bitsandbytes.__version__)
print("datasets", datasets.__version__)
if not torch.cuda.is_available():
    raise SystemExit("CUDA is not available; refusing to continue")
print("gpu", torch.cuda.get_device_name(0))
try:
    import flash_attn
    print("flash_attn", flash_attn.__version__)
except Exception as e:
    print("flash_attn not available:", e)
PY

log "setup complete (PYTHON=$PYTHON)"
