#!/usr/bin/env bash
# Pod setup for the LLM-judge experiment only: hunspell + a lean Python venv
# with transformers/accelerate. Skips the WikiText download and the heavier
# pandas/pyarrow stack that scripts/runpod/setup.sh installs for the trained
# reranker's training-data pipeline -- this experiment builds no training data.
#
# Documented image: runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04
# (Python 3.11 so hunspell==0.5.5 builds; host driver CUDA 12.4). Image torch
# is 2.4.1 -- not enough for Gemma-4. Loading google/gemma-4-E2B-it walks
# transformers.core_model_loading -> distributed.sharding_utils ->
# `from torch.distributed.tensor import DTensor`. That export exists on
# PyTorch >=2.5; torch 2.4 only has the older torch.distributed._tensor
# path. transformers 5.14.1 still hard-imports it, so pinning
# transformers>=5.5,<5.15 on image torch 2.4 (pod rwfef0kegboxvk) failed
# at model load after BEA prep.
#
# This script upgrades the venv to torch==2.5.1+cu124 *before* transformers.
# Do not use cu128 wheels or the cu128 / py3.12 image: on Community hosts
# whose driver is CUDA 12.4 those builds silently fall back to CPU.
# After the torch upgrade, transformers can be >=5.5 (Gemma-4 landed in
# 5.5; no 5.15 upper bound).
#
# torch 2.6.0+cu124 (what `torch>=2.5.1` resolved to on pod 9cfvu6gcwn11ks)
# left nvidia-cudnn-cu12 "already satisfied" from the image's system
# site-packages, then `import torch` died with libcudnn.so.9 missing.
# Pin 2.5.1 (declares nvidia deps; same cudnn 9.1 as this image),
# --ignore-installed the nvidia-* wheels into the venv, and put those
# lib dirs on LD_LIBRARY_PATH (persisted in NVIDIA_ENV_FILE for bootstrap).
set -uo pipefail

REPO_DIR="${REPO_DIR:-/workspace/spell-corrector}"
IMAGE_PYTHON="${IMAGE_PYTHON:-$(command -v python3 || command -v python)}"
VENV="${VENV:-/workspace/venv}"
NVIDIA_ENV_FILE="${NVIDIA_ENV_FILE:-/workspace/llm-judge-env.sh}"
export IMAGE_PYTHON
cd "$REPO_DIR"

log() { printf '\n=== %s (%ss) ===\n' "$1" "$SECONDS"; }
die() { echo "SETUP FAILED: $1"; exit 1; }

case "$VENV" in
  ""|"/"|"/usr"|"/usr/bin"|"/workspace") die "refusing to rm -rf VENV=$VENV" ;;
esac

use_venv_python() {
  PYTHON="$VENV/bin/python"
  export PYTHON
  export PATH="$VENV/bin:$PATH"
  mkdir -p /workspace
  printf '%s\n' "$PYTHON" > /workspace/python-interpreter
}

pip_install() {
  local log="$1"; shift
  echo "+ $PYTHON -m pip install $*" | tee "$log"
  if ! "$PYTHON" -m pip install "$@" >>"$log" 2>&1; then
    echo "----- $log -----"
    tail -80 "$log"
    return 1
  fi
  cat "$log"
  return 0
}

# --system-site-packages makes pip treat image nvidia-cudnn-cu12 as
# satisfied. The metadata is visible; libcudnn.so.9 is not on the linker
# path for a pip-installed torch. Reinstall nvidia-* into the venv and
# export those lib dirs (setup is a subprocess, so bootstrap sources
# NVIDIA_ENV_FILE).
force_install_nvidia_libs() {
  local nvidia_pkgs=()
  local line
  while IFS= read -r line; do
    [ -n "$line" ] && nvidia_pkgs+=("$line")
  done < <("$PYTHON" -m pip freeze | grep -i '^nvidia-' || true)
  if [ "${#nvidia_pkgs[@]}" -eq 0 ]; then
    nvidia_pkgs=(nvidia-cudnn-cu12)
  fi
  pip_install /tmp/pip-nvidia.log --ignore-installed --no-deps "${nvidia_pkgs[@]}" \
    || die "pip nvidia CUDA/cudnn libs into venv"
}

export_nvidia_ld_library_path() {
  local computed
  computed="$("$PYTHON" - <<'PY'
import os
import pathlib
import site

dirs = []
seen = set()
roots = [pathlib.Path(p) for p in site.getsitepackages()]
user = site.getusersitepackages()
if user:
    roots.append(pathlib.Path(user))
for root in roots:
    nvidia = root / "nvidia"
    if not nvidia.is_dir():
        continue
    for lib in list(nvidia.glob("*/lib")) + list(nvidia.glob("*/lib64")):
        if lib.is_dir():
            resolved = str(lib.resolve())
            if resolved not in seen:
                seen.add(resolved)
                dirs.append(resolved)
existing = [p for p in os.environ.get("LD_LIBRARY_PATH", "").split(":") if p and p not in seen]
print(":".join(dirs + existing))
PY
)"
  export LD_LIBRARY_PATH="$computed"
  mkdir -p "$(dirname "$NVIDIA_ENV_FILE")"
  {
    echo "# Generated by setup_llm_judge.sh — nvidia pip lib dirs for libcudnn.so.9"
    printf 'export LD_LIBRARY_PATH=%q\n' "$LD_LIBRARY_PATH"
  } > "$NVIDIA_ENV_FILE"
  echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
  echo "wrote $NVIDIA_ENV_FILE"
}

log "CUDA check ($IMAGE_PYTHON)"
nvidia-smi || echo "nvidia-smi unavailable"
"$IMAGE_PYTHON" - <<'PY' || die "CUDA not available"
import torch
print("torch", torch.__version__)
print("torch.version.cuda", torch.version.cuda)
assert torch.cuda.is_available(), "CUDA is not available; refusing to continue"
print("gpu", torch.cuda.get_device_name(0), "bf16", torch.cuda.is_bf16_supported())
PY

log "apt: hunspell"
(
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq --no-install-recommends \
    git curl ca-certificates hunspell libhunspell-dev hunspell-en-us
  pyver="$("$IMAGE_PYTHON" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
  apt-get install -y -qq --no-install-recommends \
    "python${pyver}-venv" "python${pyver}-dev" \
    || apt-get install -y -qq --no-install-recommends python3-venv python3-dev
) >/tmp/apt.log 2>&1 || { tail -30 /tmp/apt.log; die "apt"; }
log "apt done"

log "venv $VENV --system-site-packages"
rm -rf "$VENV"
"$IMAGE_PYTHON" -m venv --system-site-packages "$VENV" || die "venv"
use_venv_python
echo "venv python=$PYTHON ($($PYTHON -V 2>&1))"
if ! "$PYTHON" -m pip --version >/dev/null 2>&1; then
  "$PYTHON" -m ensurepip --upgrade || die "ensurepip"
fi

log "CUDA check (venv, image torch via system site packages)"
"$PYTHON" - <<'PY' || die "CUDA not available in venv"
import torch
print("torch", torch.__version__, "cuda avail", torch.cuda.is_available())
assert torch.cuda.is_available(), "CUDA is not available in the venv"
print("gpu", torch.cuda.get_device_name(0), "bf16", torch.cuda.is_bf16_supported())
PY

log "pip deps + hunspell into $VENV"
pip_install /tmp/pip-upgrade.log --upgrade pip || die "pip upgrade"
pip_install /tmp/pip-deps.log \
  numpy matplotlib requests pytest \
  || die "pip deps"

# DSPy drives scripts/dspy_prompt_search.py, which talks to llama-server over
# its OpenAI-compatible endpoint (via LiteLLM) and needs nothing from torch or
# transformers. `dspy` is the current distribution name; `dspy-ai` is a legacy
# alias and installing that one instead gets an outdated package.
pip_install /tmp/pip-dspy.log "dspy>=3.0" || die "pip dspy"
pip_install /tmp/pip-build.log "setuptools<60" wheel cython || die "pip build deps"
pip_install /tmp/hunspell-pip.log --no-build-isolation --force-reinstall hunspell==0.5.5 \
  || die "hunspell pip install into ${PYTHON}"
"$PYTHON" -m pip show hunspell || die "pip show hunspell"

# Gemma-4 / DTensor needs torch>=2.5. Official Runpod catalog has no
# py3.11 + cu124 image that already ships that, so install cu124 wheels
# into the venv (never cu128). Skip the download if the image already
# has a CUDA-available torch>=2.5 built for 12.4.
#
# Pin 2.5.1, not >=2.5.1: 2.6.0+cu124 from this index can skip nvidia
# deps (pytorch#148345) and then fail libcudnn.so.9 when the image's
# nvidia-cudnn-cu12 is "already satisfied" (pod 9cfvu6gcwn11ks).
log "torch==2.5.1+cu124 (DTensor / Gemma-4)"
if "$PYTHON" - <<'PY'
import sys
import torch

ver = tuple(int(p) for p in torch.__version__.split("+", 1)[0].split(".")[:2])
cuda = torch.version.cuda or ""
print(
    "pre-upgrade torch", torch.__version__,
    "cuda", cuda,
    "avail", torch.cuda.is_available(),
    "file", torch.__file__,
)
if ver >= (2, 5) and cuda.startswith("12.4") and torch.cuda.is_available():
    sys.exit(0)
sys.exit(1)
PY
then
  echo "venv already has CUDA-available torch>=2.5+cu124; skipping wheel download"
else
  pip_install /tmp/pip-torch.log --upgrade "torch==2.5.1" \
    --index-url https://download.pytorch.org/whl/cu124 \
    || die "pip torch==2.5.1+cu124"
  log "nvidia-* into venv (libcudnn.so.9)"
  force_install_nvidia_libs
fi
export_nvidia_ld_library_path

log "CUDA / DTensor check (venv torch after cu124 install)"
"$PYTHON" - <<'PY' || die "CUDA-available torch>=2.5.1+cu124 / DTensor missing"
import os
from pathlib import Path

import torch
from torch.distributed.tensor import DTensor

print("torch", torch.__version__, "file", torch.__file__)
print("torch.version.cuda", torch.version.cuda)
print("cuda avail", torch.cuda.is_available())
print("LD_LIBRARY_PATH", os.environ.get("LD_LIBRARY_PATH", ""))
ver = tuple(int(p) for p in torch.__version__.split("+", 1)[0].split(".")[:2])
cuda = torch.version.cuda or ""
assert ver >= (2, 5), (
    f"need torch>=2.5 for torch.distributed.tensor.DTensor; got {torch.__version__}"
)
assert "cu128" not in torch.__version__, (
    f"cu128 wheels fall back to CPU on CUDA 12.4 hosts; got {torch.__version__}"
)
assert cuda.startswith("12.4"), (
    f"need a cu124 build (host driver is CUDA 12.4); torch.version.cuda={cuda!r}"
)
cudnn = None
for part in os.environ.get("LD_LIBRARY_PATH", "").split(":"):
    candidate = Path(part) / "libcudnn.so.9"
    if part and candidate.exists():
        cudnn = candidate
        break
if cudnn is None:
    print("warning: libcudnn.so.9 not found on LD_LIBRARY_PATH; import may still work via RPATH")
else:
    print("libcudnn.so.9", cudnn)
assert torch.cuda.is_available(), (
    f"CUDA is not available after torch install; "
    f"torch={torch.__version__} torch.version.cuda={cuda} "
    f"LD_LIBRARY_PATH={os.environ.get('LD_LIBRARY_PATH', '')}"
)
print("DTensor", DTensor)
print("gpu", torch.cuda.get_device_name(0), "bf16", torch.cuda.is_bf16_supported())
PY

# Gemma-4 needs 5.5. torch is now >=2.5 so 5.15+ is fine; do not pin <5.15.
pip_install /tmp/pip-transformers.log "transformers>=5.5" "accelerate>=0.34" \
  || die "pip transformers/accelerate"

log "transformers / DTensor / gemma4 import check"
"$PYTHON" - <<'PY' || die "transformers cannot import DTensor/gemma4"
import torch
import transformers
import transformers.models.gemma4
from torch.distributed.tensor import DTensor
from transformers import AutoModel, AutoTokenizer
from transformers.models.gemma4.configuration_gemma4 import Gemma4Config
from transformers.utils import is_torch_available

print("torch", torch.__version__, "file", torch.__file__)
print("transformers", transformers.__version__)
parts = transformers.__version__.split(".")
major, minor = int(parts[0]), int(parts[1])
assert is_torch_available(), (
    f"transformers disabled PyTorch; torch={torch.__version__}. "
    "Need torch>=2.5.1+cu124 and transformers>=5.5."
)
assert (major, minor) >= (5, 5), (
    f"transformers {transformers.__version__} is too old for Gemma-4 "
    "(model_type gemma4 landed in 5.5)."
)
assert AutoModel is not None and AutoTokenizer is not None
assert getattr(transformers, "AutoModelForMultimodalLM", None) is not None
assert DTensor is not None
assert Gemma4Config.model_type == "gemma4"
print("DTensor", DTensor)
print("gemma4", transformers.models.gemma4.__name__, "model_type", Gemma4Config.model_type)
print("AutoModel / AutoModelForMultimodalLM import ok")
PY

log "hunspell import check"
"$PYTHON" - <<'PY' || die "import hunspell"
import hunspell
print("hunspell", hunspell.__file__)
PY

log "verifying"
"$PYTHON" - <<'PY' || die "verify"
import torch
import transformers
from transformers import AutoModel
from spelling_reranker.hunspell import default_engine

print("torch", torch.__version__, "cuda avail", torch.cuda.is_available())
print("transformers", transformers.__version__)
if not torch.cuda.is_available():
    raise SystemExit("CUDA is not available; refusing to continue")
print("gpu", torch.cuda.get_device_name(0))
assert AutoModel is not None
engine = default_engine()
assert engine.suggest("recieve"), "hunspell returned no suggestions"
print("hunspell suggest('recieve') ->", engine.suggest("recieve"))
PY

log "setup complete (PYTHON=$PYTHON)"
